# Generated by Django 4.2.4 on 2023-10-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Item',
            new_name='item',
        ),
    ]
