# Generated by Django 4.2.4 on 2023-10-12 04:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0002_rename_item_conversation_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversetionMessage',
            new_name='ConversationMessage',
        ),
    ]
