# Generated by Django 4.2.4 on 2023-10-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_rename_conversetionmessage_conversationmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='creeated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='modifieid_at',
            new_name='modified_at',
        ),
    ]
